# Generated by Django 5.2.1 on 2025-05-17 09:09

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='category',
        ),
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(upload_to=core.models.book_cover_path),
        ),
        migrations.AlterField(
            model_name='book',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to=core.models.book_pdf_path),
        ),
        migrations.DeleteModel(
            name='BookReview',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
